---
apiVersion: v1
kind: Service
metadata:
  name: {{ (printf "%s-%s" .Release.Name "app" ) | quote }}
  labels:
{{ include "mergeLabels" . | nindent 4 }}
  annotations:
{{ include "mergeAnnotations" . | nindent 4 }}
{{ with .Values.app.service.annotations }}
{{ toYaml . | nindent 4 }}
{{ end }}
spec:
  type: {{ .Values.app.service.spec.type | default "ClusterIP" | quote }}
  ports:
{{ toYaml .Values.app.service.spec.ports | indent 4 }}
  selector:
    app: {{ include "fullname_app" . }}
