{{- if not .Values.secret.existingSecret }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "secretName" .) }}
{{- if not $existingSecret }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | quote }}
{{- if .Values.secret.POSTGRES_PASSWORD }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
{{- else }}
  POSTGRES_PASSWORD: {{ include "randomPassword" . | quote }}
{{- end }}
{{- end }}
{{- end }}

